ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MODERATOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CURATOR';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT,
ADD COLUMN IF NOT EXISTS "favoriteGenres" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "communicationOptIn" BOOLEAN NOT NULL DEFAULT true;
